services:
  - type: web
    name: project-diamond-backend
    env: docker
    region: oregon
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free
