name: CI - Build & Test

env:
  FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build & run tests
        run: mvn -B -DskipTests=false clean verify

      - name: SonarCloud Scan (Maven plugin)
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests=false -Dsonar.token=${{ env.SONAR_TOKEN }}

      - name: Upload test results (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

    
